services:
  akvoformprint:
    build: .
    volumes:
      - ./output:/app/output
    environment:
      - PYTHONPATH=/app/src
    command: python examples/render_example.py

  test:
    build: .
    volumes:
      - .:/app
    command: ./run_tests.sh
